# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(800, 600)
        Login.setStyleSheet("#login_user:hover , #login_pwd:hover , #btn_login_submit:hover , #btn_login_cancel:hover{\n"
"border-radius:20px;\n"
"background-color:white;\n"
"}\n"
"#login_user , #login_pwd , #btn_login_submit , #btn_login_cancel{\n"
"border-radius:20px;\n"
"background-color:#cccccc;\n"
"height:31px;\n"
"}\n"
"\n"
"#label_2{\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"background-color:gray;\n"
"color:white;\n"
"}\n"
"#label{\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"background-color:#cccccc;\n"
"}")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(30, 30, 301, 521))
        font = QtGui.QFont()
        font.setPointSize(33)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(330, 30, 411, 521))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.login_user = QtWidgets.QLineEdit(Login)
        self.login_user.setGeometry(QtCore.QRect(370, 130, 331, 31))
        self.login_user.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login_user.setObjectName("login_user")
        self.login_pwd = QtWidgets.QLineEdit(Login)
        self.login_pwd.setGeometry(QtCore.QRect(370, 180, 331, 31))
        self.login_pwd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.login_pwd.setObjectName("login_pwd")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Login)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(370, 230, 331, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_login_submit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_login_submit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/icons8-arrow-30.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_login_submit.setIcon(icon)
        self.btn_login_submit.setObjectName("btn_login_submit")
        self.horizontalLayout.addWidget(self.btn_login_submit)
        self.btn_login_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_login_cancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icon/icons8-close-window-94.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_login_cancel.setIcon(icon1)
        self.btn_login_cancel.setObjectName("btn_login_cancel")
        self.horizontalLayout.addWidget(self.btn_login_cancel)
        self.login_msg = QtWidgets.QLabel(Login)
        self.login_msg.setGeometry(QtCore.QRect(350, 370, 361, 81))
        self.login_msg.setText("")
        self.login_msg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_msg.setObjectName("login_msg")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Scraping - Login"))
        self.label.setText(_translate("Login", "Scraping manager"))
        self.login_user.setPlaceholderText(_translate("Login", "Username"))
        self.login_pwd.setPlaceholderText(_translate("Login", "Password"))
        self.btn_login_submit.setText(_translate("Login", "Login"))
        self.btn_login_cancel.setText(_translate("Login", "Cancel"))
